[package]
name = "graphics"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "0.18.2"
gfx_window_glutin = "0.31.0"
gfx_device_gl = "0.16"
glutin = "0.21"
thiserror = "*"
nalgebra = "*"

[dev-dependencies]
specs = "*"
specs-derive = "*"
