[package]
name = "graphics"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.22"
wgpu = "0.4"
thiserror = "1.0"
nalgebra = "0.20"

[dev-dependencies]
specs = "0.16"
specs-derive = "0.4"
anyhow = "1.0"

[build-dependencies]
shaderc = "0.6"