[package]
name = "graphics"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "*"
gfx_window_glutin = "*"
gfx_device_gl = "*"
glutin = "*"
quick-error = "*"
nalgebra = "*"
time = "*"

[dev-dependencies]
specs = "*"
specs-derive = "*"
