[package]
name = "asteroids"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
graphics = { path = "./graphics" }
specs = "0.16"
specs-derive = "0.4"
nphysics2d = "0.17"
ncollide2d = "0.24"
nalgebra = "0.22"
rand = "0.7"
anyhow = "1.0"