[package]
name = "asteroids"
version = "0.1.0"
authors = ["Peter Higley <phigley@gmail.com>"]

[workspace]

[dependencies]
graphics = { path = "./graphics" }
specs = "*"
specs-derive = "*"
quick-error = "*"
ncollide2d = "*"
nalgebra = "*"
rand = "*"